name: Node CI

on: [push, pull_request]

jobs:
  lint-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node-version: [16.x, 18.x, 20.x]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - run: yarn --immutable
      - run: yarn build
      - run: yarn lint
      - run: yarn test
